#!/bin/bash

NAME=Python
BASE_REPO=python
VARIANTS=(browsers node node-browsers)

IMAGE_CUSTOMIZATIONS=$(cat <<'EOF'

# Install pipenv
RUN sudo pip install pipenv

#install poetry
RUN sudo curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python

EOF
)

source ../shared/images/generate-node.sh
source ../shared/images/generate.sh
